/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AktiviteRouteImport } from './routes/aktivite'
import { Route as BolgelerRouteImport } from './routes/bolgeler'
import { Route as EslesmeRouteImport } from './routes/eslesme'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as GorevlerRouteImport } from './routes/gorevler'
import { Route as HaritaRouteImport } from './routes/harita'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ProfilOlusturRouteImport } from './routes/profil-olustur'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AktiviteRoute = AktiviteRouteImport.update({
  id: '/aktivite',
  path: '/aktivite',
  getParentRoute: () => rootRouteImport,
} as any)
const BolgelerRoute = BolgelerRouteImport.update({
  id: '/bolgeler',
  path: '/bolgeler',
  getParentRoute: () => rootRouteImport,
} as any)
const EslesmeRoute = EslesmeRouteImport.update({
  id: '/eslesme',
  path: '/eslesme',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const GorevlerRoute = GorevlerRouteImport.update({
  id: '/gorevler',
  path: '/gorevler',
  getParentRoute: () => rootRouteImport,
} as any)
const HaritaRoute = HaritaRouteImport.update({
  id: '/harita',
  path: '/harita',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilOlusturRoute = ProfilOlusturRouteImport.update({
  id: '/profil-olustur',
  path: '/profil-olustur',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktivite': typeof AktiviteRoute
  '/bolgeler': typeof BolgelerRoute
  '/eslesme': typeof EslesmeRoute
  '/gizlilik': typeof GizlilikRoute
  '/gorevler': typeof GorevlerRoute
  '/harita': typeof HaritaRoute
  '/panel': typeof PanelRoute
  '/profil': typeof ProfilRoute
  '/profil-olustur': typeof ProfilOlusturRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivite': typeof AktiviteRoute
  '/bolgeler': typeof BolgelerRoute
  '/eslesme': typeof EslesmeRoute
  '/gizlilik': typeof GizlilikRoute
  '/gorevler': typeof GorevlerRoute
  '/harita': typeof HaritaRoute
  '/panel': typeof PanelRoute
  '/profil': typeof ProfilRoute
  '/profil-olustur': typeof ProfilOlusturRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktivite': typeof AktiviteRoute
  '/bolgeler': typeof BolgelerRoute
  '/eslesme': typeof EslesmeRoute
  '/gizlilik': typeof GizlilikRoute
  '/gorevler': typeof GorevlerRoute
  '/harita': typeof HaritaRoute
  '/panel': typeof PanelRoute
  '/profil': typeof ProfilRoute
  '/profil-olustur': typeof ProfilOlusturRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktivite'
    | '/bolgeler'
    | '/eslesme'
    | '/gizlilik'
    | '/gorevler'
    | '/harita'
    | '/panel'
    | '/profil'
    | '/profil-olustur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktivite'
    | '/bolgeler'
    | '/eslesme'
    | '/gizlilik'
    | '/gorevler'
    | '/harita'
    | '/panel'
    | '/profil'
    | '/profil-olustur'
  id:
    | '__root__'
    | '/'
    | '/aktivite'
    | '/bolgeler'
    | '/eslesme'
    | '/gizlilik'
    | '/gorevler'
    | '/harita'
    | '/panel'
    | '/profil'
    | '/profil-olustur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktiviteRoute: typeof AktiviteRoute
  BolgelerRoute: typeof BolgelerRoute
  EslesmeRoute: typeof EslesmeRoute
  GizlilikRoute: typeof GizlilikRoute
  GorevlerRoute: typeof GorevlerRoute
  HaritaRoute: typeof HaritaRoute
  PanelRoute: typeof PanelRoute
  ProfilRoute: typeof ProfilRoute
  ProfilOlusturRoute: typeof ProfilOlusturRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivite': {
      id: '/aktivite'
      path: '/aktivite'
      fullPath: '/aktivite'
      preLoaderRoute: typeof AktiviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolgeler': {
      id: '/bolgeler'
      path: '/bolgeler'
      fullPath: '/bolgeler'
      preLoaderRoute: typeof BolgelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eslesme': {
      id: '/eslesme'
      path: '/eslesme'
      fullPath: '/eslesme'
      preLoaderRoute: typeof EslesmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gorevler': {
      id: '/gorevler'
      path: '/gorevler'
      fullPath: '/gorevler'
      preLoaderRoute: typeof GorevlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harita': {
      id: '/harita'
      path: '/harita'
      fullPath: '/harita'
      preLoaderRoute: typeof HaritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil-olustur': {
      id: '/profil-olustur'
      path: '/profil-olustur'
      fullPath: '/profil-olustur'
      preLoaderRoute: typeof ProfilOlusturRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktiviteRoute: AktiviteRoute,
  BolgelerRoute: BolgelerRoute,
  EslesmeRoute: EslesmeRoute,
  GizlilikRoute: GizlilikRoute,
  GorevlerRoute: GorevlerRoute,
  HaritaRoute: HaritaRoute,
  PanelRoute: PanelRoute,
  ProfilRoute: ProfilRoute,
  ProfilOlusturRoute: ProfilOlusturRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
